networks:
  main:
    driver: bridge

volumes:
  wp-db:
    driver_opts:
      type: none
      device: /home/tom/data/wp-db
      o: bind
  wp-sites:
    driver_opts:
      type: none
      device: /home/tom/data/wp-sites
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - main
    volumes:
      - wp-sites:/var/www/html
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_HOST=${DB_HOST}
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_password
      - wp_email
    networks:
      - main
    volumes:
      - wp-sites:/var/www/html
    restart: always
    depends_on:
      - mariadb
      - redis

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - db_name
      - db_user
      - db_password
    networks:
      - main
    volumes:
      - wp-db:/var/lib/mysql
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    networks:
      - main
    restart: always
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
        - wp-sites:/var/www/html
    secrets:
      - ftp_user
      - ftp_password
    ports:
        - "21:21"
        - "20:20"
        - "50000-50100:50000-50100"
    depends_on:
        - wordpress
    restart: always
  static-site:
    container_name: static-site
    build: ./requirements/bonus/static-site
    ports:
      - "8081:8081"
    networks:
      - main
    restart: always


secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_email:
    file: ../secrets/wp_email.txt
  ftp_user:
    file: ../secrets/ftp_user.txt
  ftp_password:
    file: ../secrets/ftp_password.txt