networks:
  main:
    driver: bridge

volumes:
  wp-db:
    driver_opts:
      type: none
      device: /home/tom/data/wp-db
      o: bind
  wp-sites:
    driver_opts:
      type: none
      device: /home/tom/data/wp-sites
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks:
      - main
    volumes:
      - wp-sites:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DB_HOST=${DB_HOST}
    secrets:
      - db_name
      - db_user
      - db_password
      - wp_admin_user
      - wp_admin_password
      - wp_admin_email
      - wp_user
      - wp_password
      - wp_email
    networks:
      - main
    volumes:
      - wp-sites:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    secrets:
      - db_name
      - db_user
      - db_password
    networks:
      - main
    volumes:
      - wp-db:/var/lib/mysql
    restart: always


secrets:
  db_name:
    file: ../secrets/db_name.txt
  db_user:
    file: ../secrets/db_user.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_user:
    file: ../secrets/wp_admin_user.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_admin_email:
    file: ../secrets/wp_admin_email.txt
  wp_user:
    file: ../secrets/wp_user.txt
  wp_password:
    file: ../secrets/wp_password.txt
  wp_email:
    file: ../secrets/wp_email.txt